require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CrushesController do

  # This should return the minimal set of attributes required to create a valid
  # Crush. As you add validations to Crush, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CrushesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all crushes as @crushes" do
      crush = Crush.create! valid_attributes
      get :index, {}, valid_session
      assigns(:crushes).should eq([crush])
    end
  end

  describe "GET show" do
    it "assigns the requested crush as @crush" do
      crush = Crush.create! valid_attributes
      get :show, {:id => crush.to_param}, valid_session
      assigns(:crush).should eq(crush)
    end
  end

  describe "GET new" do
    it "assigns a new crush as @crush" do
      get :new, {}, valid_session
      assigns(:crush).should be_a_new(Crush)
    end
  end

  describe "GET edit" do
    it "assigns the requested crush as @crush" do
      crush = Crush.create! valid_attributes
      get :edit, {:id => crush.to_param}, valid_session
      assigns(:crush).should eq(crush)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Crush" do
        expect {
          post :create, {:crush => valid_attributes}, valid_session
        }.to change(Crush, :count).by(1)
      end

      it "assigns a newly created crush as @crush" do
        post :create, {:crush => valid_attributes}, valid_session
        assigns(:crush).should be_a(Crush)
        assigns(:crush).should be_persisted
      end

      it "redirects to the created crush" do
        post :create, {:crush => valid_attributes}, valid_session
        response.should redirect_to(Crush.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved crush as @crush" do
        # Trigger the behavior that occurs when invalid params are submitted
        Crush.any_instance.stub(:save).and_return(false)
        post :create, {:crush => {  }}, valid_session
        assigns(:crush).should be_a_new(Crush)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Crush.any_instance.stub(:save).and_return(false)
        post :create, {:crush => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested crush" do
        crush = Crush.create! valid_attributes
        # Assuming there are no other crushes in the database, this
        # specifies that the Crush created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Crush.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => crush.to_param, :crush => { "these" => "params" }}, valid_session
      end

      it "assigns the requested crush as @crush" do
        crush = Crush.create! valid_attributes
        put :update, {:id => crush.to_param, :crush => valid_attributes}, valid_session
        assigns(:crush).should eq(crush)
      end

      it "redirects to the crush" do
        crush = Crush.create! valid_attributes
        put :update, {:id => crush.to_param, :crush => valid_attributes}, valid_session
        response.should redirect_to(crush)
      end
    end

    describe "with invalid params" do
      it "assigns the crush as @crush" do
        crush = Crush.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Crush.any_instance.stub(:save).and_return(false)
        put :update, {:id => crush.to_param, :crush => {  }}, valid_session
        assigns(:crush).should eq(crush)
      end

      it "re-renders the 'edit' template" do
        crush = Crush.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Crush.any_instance.stub(:save).and_return(false)
        put :update, {:id => crush.to_param, :crush => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested crush" do
      crush = Crush.create! valid_attributes
      expect {
        delete :destroy, {:id => crush.to_param}, valid_session
      }.to change(Crush, :count).by(-1)
    end

    it "redirects to the crushes list" do
      crush = Crush.create! valid_attributes
      delete :destroy, {:id => crush.to_param}, valid_session
      response.should redirect_to(crushes_url)
    end
  end

end
